// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb-OT3WRdYRjlk2xZT4q9NJkP88Wnn19o',
    appId: '1:682523626792:web:e4bc5bd979da059bb5d41d',
    messagingSenderId: '682523626792',
    projectId: 'roboticsclub-f6be6',
    authDomain: 'roboticsclub-f6be6.firebaseapp.com',
    storageBucket: 'roboticsclub-f6be6.appspot.com',
    measurementId: 'G-3ZSRF8Y2ZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGRMBQey0WN9h05gWHLhQY7HtR24QkMjc',
    appId: '1:682523626792:android:f15c7f77d8f92f64b5d41d',
    messagingSenderId: '682523626792',
    projectId: 'roboticsclub-f6be6',
    storageBucket: 'roboticsclub-f6be6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZMYdOGHlVT7KjB1UsoW9GRzyPhgokyZA',
    appId: '1:682523626792:ios:f2a9312826ccfcbbb5d41d',
    messagingSenderId: '682523626792',
    projectId: 'roboticsclub-f6be6',
    storageBucket: 'roboticsclub-f6be6.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZMYdOGHlVT7KjB1UsoW9GRzyPhgokyZA',
    appId: '1:682523626792:ios:5c75e42c391804fab5d41d',
    messagingSenderId: '682523626792',
    projectId: 'roboticsclub-f6be6',
    storageBucket: 'roboticsclub-f6be6.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
